#!/bin/sh

COMMIT_RANGE='HEAD'
CHANGED_FILES=$(git diff --name-only --diff-filter=ACMRTUXB "${COMMIT_RANGE}" | grep ".php\$")

if [ -z "$CHANGED_FILES" ]
then
  exit 0;
fi

echo -e "\e[0;33mValidating php-cs-fixer rules...\e[0m"

if ! echo "${CHANGED_FILES}" | grep -qE "^(\\.php_cs(\\.dist)?|composer\\.lock)$"; then
  EXTRA_ARGS=$(printf -- '--path-mode=intersection\n--\n%s' "${CHANGED_FILES}");
else
  EXTRA_ARGS='';
fi

docker exec -t mcatalog_php php vendor/bin/php-cs-fixer fix --config=./.php-cs-fixer.dist.php -v --dry-run --using-cache=no ${EXTRA_ARGS}

### Result banner

RESULT=$?

if [ $RESULT -eq 0 ]
then
  /bin/echo -e "\e[30;42m                                                                          \e[0m"
  /bin/echo -e "\e[30;42m [OK] Php-cs-fixer rules are valid                                        \e[0m"
  /bin/echo -e "\e[30;42m                                                                          \e[0m"
else
  /bin/echo -e "\e[30;41m                                                                          \e[0m"
  /bin/echo -e "\e[30;41m [ERROR] Php-cs-fixer rules are invalid!                                  \e[0m"
  /bin/echo -e "\e[30;41m                                                                          \e[0m"
fi

exit $RESULT
