# from https://github.com/ger86/symfony-docker

version: "3"

services:
    mcatalog_db:
        container_name: mcatalog_db
        hostname: mcatalog_db
        image: mysql:8.0.23
        platform: linux/x86_64
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - ./mysql/volume:/var/lib/mysql:delegated
        environment:
            MYSQL_ROOT_HOST: "%"
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - 33061:3306
        networks:
            - proxynet

    mcatalog_php:
        container_name: mcatalog_php
        hostname: mcatalog_php
        build:
            context: ./php
            args:
                TIMEZONE: ${TIMEZONE}
                GIT_EMAIL: ${GIT_EMAIL}
                GIT_NAME: ${GIT_NAME}
        volumes:
            - ../:/var/www/mediacatalog/
            - ./php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
        environment:
            PHP_CS_FIXER_IGNORE_ENV: 1
            PHP_CS_FIXER_ALLOW_XDEBUG: 1
            PHP_IDE_CONFIG: serverName=mcatalog-php
            PSALM_ALLOW_XDEBUG: 1;
        stdin_open: true
        tty: true
        command:
            - /bin/bash
        networks:
            - proxynet

    mcatalog_ngnix:
        container_name: mcatalog_nginx
        hostname: mcatalog_nginx
        links:
            - mcatalog_php
        build:
            context: ./nginx
        volumes:
            - ../:/var/www/mediacatalog/
        ports:
            - 801:80
        networks:
            - proxynet
        env_file:
            - .env.nginx

networks:
    proxynet:
        name: mcatalog_network
        ipam:
            config:
                -   subnet: 172.76.30.0/24
                    gateway: 172.76.30.1