<?php

namespace DevRunDebug\MediaCatalog;

use DevRunDebug\MediaCatalog\Type\EnumLocalizationType;
use Doctrine\DBAL\Types\Type;
use Symfony\Bundle\FrameworkBundle\Kernel\MicroKernelTrait;
use Symfony\Component\HttpKernel\Kernel as BaseKernel;

class Kernel extends BaseKernel
{
    use MicroKernelTrait;

    public function boot(): void
    {
        $this->registerDBALTypes();
        parent::boot(); // TODO: Change the autogenerated stub
    }

    private function registerDBALTypes()
    {
        Type::addType(EnumLocalizationType::NAME, EnumLocalizationType::class);
    }
}
